
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author vladi
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelValores = new javax.swing.JPanel();
        labelResultado = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        labelNum2 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        labelNum1 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        panelOperaciones = new javax.swing.JPanel();
        botonSumar = new javax.swing.JButton();
        botonRestar = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        botonReset = new javax.swing.JButton();
        botonConversion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(0, 102, 102));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Calculadora Basica");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 304, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        getContentPane().add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 530, 150));

        panelValores.setBackground(new java.awt.Color(0, 153, 153));
        panelValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(255, 255, 255));
        labelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultado.setText("Resultado");
        panelValores.add(labelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 80, 50));

        txtNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });
        txtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum1KeyTyped(evt);
            }
        });
        panelValores.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 120, 30));

        labelNum2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNum2.setForeground(new java.awt.Color(255, 255, 255));
        labelNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum2.setText("Valor 2:");
        panelValores.add(labelNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 50));

        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        panelValores.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 170, 50));

        labelNum1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNum1.setForeground(new java.awt.Color(255, 255, 255));
        labelNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum1.setText("Valor 1:");
        panelValores.add(labelNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, 50));

        txtNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum2ActionPerformed(evt);
            }
        });
        txtNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum2KeyTyped(evt);
            }
        });
        panelValores.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, 30));

        getContentPane().add(panelValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 290));

        panelOperaciones.setBackground(new java.awt.Color(0, 51, 51));
        panelOperaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonSumar.setText("Sumar");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        panelOperaciones.add(botonSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, -1));

        botonRestar.setText("Restar");
        botonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestarActionPerformed(evt);
            }
        });
        panelOperaciones.add(botonRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 90, -1));

        botonMultiplicar.setText("Multiplicar");
        botonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicarActionPerformed(evt);
            }
        });
        panelOperaciones.add(botonMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, -1));

        botonDividir.setText("Dividir");
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });
        panelOperaciones.add(botonDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, -1));

        botonReset.setText("Resetear");
        botonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResetActionPerformed(evt);
            }
        });
        panelOperaciones.add(botonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 110, 40));

        botonConversion.setText("Farenheit a Celcius");
        botonConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConversionActionPerformed(evt);
            }
        });
        panelOperaciones.add(botonConversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, -1));

        getContentPane().add(panelOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 260, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void txtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum2ActionPerformed

    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
        validarCampos();
        dividirValores();
    }//GEN-LAST:event_botonDividirActionPerformed

    private void txtNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum1KeyTyped
        char numeros = evt.getKeyChar();
        
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtNum1KeyTyped

    private void txtNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum2KeyTyped
        char numeros = evt.getKeyChar();
        
        if ((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')) {
            JOptionPane.showMessageDialog(null, "Favor ingresar numeros para realizar la operacion.");
            evt.consume();
        }
    }//GEN-LAST:event_txtNum2KeyTyped

    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        validarCampos();
        sumarValores();
    }//GEN-LAST:event_botonSumarActionPerformed

    private void botonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResetActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_botonResetActionPerformed

    private void botonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestarActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_botonRestarActionPerformed

    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_botonMultiplicarActionPerformed

    private void botonConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConversionActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Solo se tomara en cuenta el primer valor.");
        deFarenheitACelsius();
    }//GEN-LAST:event_botonConversionActionPerformed
    
    private void validarCampos() {
        
        if (txtNum1.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar el numero uno, el campo esta vacio.");
            txtNum1.requestFocus();
        } else if (txtNum2.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "Favor ingresar el numero dos, el campo esta vacio.");
            txtNum2.requestFocus();
        }
        
    }
    
    private void sumarValores() {
        Calculadora cal = new Calculadora();
        Double respuesta = cal.sumar(Double.parseDouble(txtNum1.getText()), Double.parseDouble(txtNum2.getText()));
        txtResultado.setText(respuesta + "");
    }
    
    private void restarValores(){
        Calculadora cal = new Calculadora();
        Double resultado = cal.restar(Double.parseDouble(txtNum1.getText()), Double.parseDouble(txtNum2.getText()));
        txtResultado.setText(resultado + "");
    }
    
    private void multiplicarValores(){
        Calculadora cal = new Calculadora();
        Double resultado = cal.multiplicar(Double.parseDouble(txtNum1.getText()), Double.parseDouble(txtNum2.getText()));
        txtResultado.setText(resultado + "");
    }
    
    private void dividirValores(){
        Calculadora cal = new Calculadora();
        Double resultado = cal.dividir(Double.parseDouble(txtNum1.getText()), Double.parseDouble(txtNum2.getText()));
        txtResultado.setText(resultado + "");
    }
    
    private void limpiarCampos(){
        txtNum1.setText("");
        txtNum2.setText("");
        txtResultado.setText("");
        txtNum1.requestFocus();
    }
    
    private void deFarenheitACelsius(){
        Calculadora cal = new Calculadora();
        Double resultado = cal.convertir(Double.parseDouble(txtNum1.getText()));
        txtResultado.setText(resultado + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConversion;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonReset;
    private javax.swing.JButton botonRestar;
    private javax.swing.JButton botonSumar;
    private javax.swing.JLabel labelNum1;
    private javax.swing.JLabel labelNum2;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelOperaciones;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelValores;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
